// SHOWCASE MODE - Mock API using pre-generated mesh data
import type {
  ImageUploadResponse,
  SurfaceResponse,
  HealthCheckResponse,
} from './types'
import { MOCK_MESH } from './mock-data'

// Simulate API delays for realistic UX
const UPLOAD_DELAY = 800;
const GENERATION_DELAY = 3000;

let activeMeshRequest: AbortController | null = null

export function cancelPendingRequests() {
  if (activeMeshRequest) {
    activeMeshRequest.abort()
    activeMeshRequest = null
  }
}

// Simulate image upload (instant - we're using pre-loaded image)
export async function uploadImage(file: File): Promise<ImageUploadResponse> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        success: true,
        image_id: 'demo-image-' + Date.now()
      })
    }, UPLOAD_DELAY)
  })
}

// Simulate surface generation with mock mesh
export async function generateSurface(
  imageId: string,
  downsampleScale: number = 0.25,
  smoothStrength: number = 5,
  zScale: number = 1.0
): Promise<SurfaceResponse> {
  return new Promise((resolve, reject) => {
    cancelPendingRequests()
    activeMeshRequest = new AbortController()

    const timeout = setTimeout(() => {
      if (activeMeshRequest?.signal.aborted) {
        reject(new Error('Generation cancelled'))
        return
      }

      // Return mock mesh data
      const vertices = MOCK_MESH.vertices.map(v => ({
        x: v.x,
        y: v.y,
        z: v.z * zScale, // Apply z-scale parameter
      }))

      const faces = MOCK_MESH.indices.map(f => ({
        indices: [f.v0, f.v1, f.v2],
      }))

      const vertexColors = MOCK_MESH.vertex_colors

      activeMeshRequest = null
      resolve({
        success: true,
        mesh: { vertices, faces, vertexColors }
      })
    }, GENERATION_DELAY)

    if (activeMeshRequest?.signal.aborted) {
      clearTimeout(timeout)
      reject(new Error('Generation cancelled'))
    }
  })
}

// Mock export (just simulates download)
export async function exportMesh(
  imageId: string,
  zScale: number,
  smoothStrength: number,
  downsampleScale: number,
  scaleStrength: number,
  sharpenStrength: number
): Promise<{ success: boolean; message?: string }> {
  return new Promise((resolve) => {
    setTimeout(() => {
      // In a real app, generate OBJ file content
      const objContent = `# Exported 3D Mesh\n# Generated by Image2Surface Showcase\ng mesh\n`
      
      const blob = new Blob([objContent], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.setAttribute('download', 'mesh.obj')
      document.body.appendChild(link)
      link.click()
      link.remove()
      window.URL.revokeObjectURL(url)
      
      resolve({ success: true })
    }, 1000)
  })
}

// Mock health check
export async function healthCheck(): Promise<HealthCheckResponse> {
  return {
    status: 'healthy',
    message: 'Image2Surface Showcase is running'
  }
}